package apply

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

func detectOpenPorts() []PortRule {
	out, err := exec.Command("ufw", "status").Output()
	if err != nil {
		return nil
	}
	var rules []PortRule
	for _, line := range strings.Split(string(out), "\n") {
		if strings.Contains(line, "(v6)") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 || fields[1] != "ALLOW" {
			continue
		}
		dest := fields[0]
		proto := "both"
		portSpec := dest
		if idx := strings.LastIndex(dest, "/"); idx >= 0 {
			portSpec = dest[:idx]
			proto = dest[idx+1:]
		}
		var from, to string
		if idx := strings.Index(portSpec, ":"); idx >= 0 {
			from = portSpec[:idx]
			to = portSpec[idx+1:]
		} else {
			from = portSpec
		}
		if ValidateNetPort(from) != nil {
			continue
		}
		rules = append(rules, PortRule{From: from, To: to, Protocol: proto, Existing: true})
	}
	return rules
}

func deleteFirewallRules(rules []PortRule) error {
	for _, r := range rules {
		if r.Protocol == "both" {
			for _, proto := range []string{"tcp", "udp"} {
				spec := r.From
				if r.To != "" && r.To != r.From {
					spec = r.From + ":" + r.To
				}
				if out, err := exec.Command("ufw", "delete", "allow", spec+"/"+proto).CombinedOutput(); err != nil {
					return fmt.Errorf("ufw delete allow %s/%s: %w\n%s", spec, proto, err, out)
				}
			}
		} else {
			spec := r.UFWSpec()
			if out, err := exec.Command("ufw", "delete", "allow", spec).CombinedOutput(); err != nil {
				return fmt.Errorf("ufw delete allow %s: %w\n%s", spec, err, out)
			}
		}
	}
	return nil
}

func applyFirewallRules(rules []PortRule) error {
	for _, r := range rules {
		if r.Protocol == "both" {
			for _, proto := range []string{"tcp", "udp"} {
				spec := r.From
				if r.To != "" && r.To != r.From {
					spec = r.From + ":" + r.To
				}
				if out, err := exec.Command("ufw", "allow", spec+"/"+proto).CombinedOutput(); err != nil {
					return fmt.Errorf("ufw allow %s/%s: %w\n%s", spec, proto, err, out)
				}
			}
		} else {
			spec := r.UFWSpec()
			if out, err := exec.Command("ufw", "allow", spec).CombinedOutput(); err != nil {
				return fmt.Errorf("ufw allow %s: %w\n%s", spec, err, out)
			}
		}
	}
	return nil
}

func writeFail2banConfig(preset string) error {
	var sb strings.Builder
	sb.WriteString("# Generated by boltx\n\n")
	if preset == "ssh" || preset == "all" {
		sb.WriteString("[sshd]\nenabled  = true\nmaxretry = 5\nbantime  = 3600\n\n")
	}
	if preset == "web" || preset == "all" {
		sb.WriteString("[nginx-http-auth]\nenabled  = true\nmaxretry = 5\nbantime  = 3600\n\n")
		sb.WriteString("[traefik-auth]\nenabled  = true\nmaxretry = 5\nbantime  = 3600\n\n")
	}
	if err := os.MkdirAll("/etc/fail2ban", 0755); err != nil {
		return fmt.Errorf("create /etc/fail2ban: %w", err)
	}
	return os.WriteFile("/etc/fail2ban/jail.local", []byte(sb.String()), 0644)
}

func enableFail2ban() error {
	if out, err := exec.Command("systemctl", "enable", "fail2ban").CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl enable fail2ban: %w\n%s", err, out)
	}
	if out, err := exec.Command("systemctl", "start", "fail2ban").CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl start fail2ban: %w\n%s", err, out)
	}
	return nil
}

func disableFail2ban() error {
	if out, err := exec.Command("systemctl", "stop", "fail2ban").CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl stop fail2ban: %w\n%s", err, out)
	}
	if out, err := exec.Command("systemctl", "disable", "fail2ban").CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl disable fail2ban: %w\n%s", err, out)
	}
	return nil
}

func detectFail2banActive() bool {
	out, err := exec.Command("systemctl", "is-active", "fail2ban").Output()
	return err == nil && strings.TrimSpace(string(out)) == "active"
}
