Output boltx.gif

Set Shell "bash"
Set FontSize 46
Set Width 1900
Set Height 800

Env VHS_NO_SANDBOX "true"

Sleep 1s

Type "go run ."   
Enter

Sleep 5s

Type "?"
Sleep 2s

Type "t" #change to teal theme
Sleep 1s
Type "t" #change to Amber theme
Sleep 1s
Type "t" #change to Purple theme
Sleep 1s
Type "t" #change to teal theme
Sleep 1s
Type "t" #change to Amber theme
Sleep 1s
Type "t" #change to Purple theme
Sleep 1s

Type "?"
Sleep 2s

Down
Sleep 1s
Enter

Sleep 1s